export const bankOptions = [
  { value: "Banco de Venezuela (BDV)", label: "Banco de Venezuela (BDV)", img: "/images/banks/0102-bdv.png", },
  { value: "Banco Mercantil", label: "Banco Mercantil", img: "/images/banks/0105-mercantil.png" },
  { value: "Banesco Banco Universal", label: "Banesco", img: "/images/banks/0134-banesco.png" },
  { value: "Bancamiga", label: "Bancamiga", img: "/images/banks/0172-bancamiga.png" },
  { value: "Banco Provincial (BBVA)", label: "Banco Provincial (BBVA)", img: "/images/banks/0108-provincial.png" },
  { value: "Banco Nacional de Crédito (BNC)", label: "Banco Nacional de Crédito (BNC)", img: "/images/banks/0191-bnc.png" },
  { value: "Banco Venezolano de Crédito (BVC)", label: "Banco Venezolano de Crédito (BVC)", img: "/images/banks/0104-bvc.png" },
  { value: "Bancaribe", label: "Bancaribe", img: "/images/banks/0114-bancaribe.png" },
  { value: "Banco Exterior", label: "Banco Exterior", img: "/images/banks/0115-exterior.png" },
  { value: "Banco Caroní", label: "Banco Caroní", img: "/images/banks/0128-caroni.png" },
  { value: "Sofitasa", label: "Sofitasa", img: "/images/banks/0137-sofitasa.png" },
  { value: "Banco Plaza", label: "Banco Plaza", img: "/images/banks/0138-plaza.png" },
  { value: "Bangente", label: "Bangente", img: "/images/banks/0146-bangente.png" },
  { value: "Banco Fondo Común (BFC)", label: "Fondo Común (BFC)", img: "/images/banks/0151-bfc.png" },
  { value: "100% Banco", label: "100% Banco", img: "/images/banks/0156-100banco.png" },
  { value: "Del Sur Banco Universal", label: "Del Sur", img: "/images/banks/0157-delsur.png" },
  { value: "Banco del Tesoro", label: "Banco del Tesoro", img: "/images/banks/0163-tesoro.png" },
  { value: "Banco Agrícola de Venezuela", label: "Banco Agrícola de Venezuela", img: "/images/banks/0166-agricola.png" },
  { value: "Bancrecer", label: "Bancrecer", img: "/images/banks/0168-bancrecer.png" },
  { value: "Mi Banco, Banco Microfinanciero C.A", label: "Mi Banco, Banco Microfinanciero C.A", img: "/images/banks/0169-mibanco.png" },
  { value: "Banco Activo", label: "Banco Activo", img: "/images/banks/0171-activo.png" },
  { value: "Banplus", label: "Banplus", img: "/images/banks/0174-banplus.png" },
  { value: "Banco Bicentenario del Pueblo", label: "Banco Bicentenario del Pueblo", img: "/images/banks/0175-bicentenario.png" },
  { value: "Banco de la Fuerza Armada Nacional Bolivariana (BANFANB)", label: "BANFANB", img: "/images/banks/0177-banfanb.png" },
];
